#!/bin/bash
######################################################
## Compatible with RedHat/CentOS Debian/Ubuntu SUSE ##
######################################################

# Support chkconfig on RedHat/CentOS
# chkconfig:   2345 55 45
# description: zabbix_agentd
# processname: zabbix_agentd
# config:      /usr/local/zabbix/etc/zabbix_agentd.conf
# pidfile:     /var/run/zabbix_agentd.pid

# Support Linux Standard Base Core Specification 3.2
### BEGIN INIT INFO
# Provides:          zabbix_agentd
# Required-Start:    $local_fs $syslog $network
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 S 1 6
# Short-Description: start/stop zabbix_agentd daemon
# Description:       zabbix_agentd is monitor agent
### END INIT INFO

#debug
#set -x
#check unbound variables
#set -u
# Scripts PATH enviroment
export PATH='/usr/bin:/bin:/usr/sbin:/sbin'
# disable core dump
ulimit -c 0
# return value
RETVAL=0
# nginx general config
PROG='zabbix_agentd'
SYMLINK=$(readlink -f /usr/local/zabbix)
BASEDIR=${SYMLINK:-/usr/local/zabbix}
DAEMON="${BASEDIR}/sbin/$PROG"
CONF="${BASEDIR}/etc/${PROG}.conf"
PIDFILE="/var/run/${PROG}.pid"
LOCKFILE="/var/lock/$PROG"
# nginx start timeout milliscond
STARTTIME=10000
# nginx stop timeout milliscond
STOPTIME=10000

#Common Function
color_msg(){
    local COLOR=$1
    local MSG=$2
    OFFSET="\033[60G"
    NORMAL="\033[0m"
    case $COLOR in
        red)
            COLOR="\033[1;40;31m"
            ;;
        green)
            COLOR="\033[1;40;32m"
            ;;
        yellow)
            COLOR="\033[1;40;33m"
            ;;
        *)
            COLOR="\033[0m"
            ;;
    esac
    echo -en "$OFFSET [$COLOR $MSG $NORMAL"
    echo     "]"
}

start() {
    echo -n "Starting $PROG : "
    PROC_PID=$(pgrep -P 1 -u zabbix ^$PROG)
    if [ -n "$PROC_PID" ]; then
        echo -n "is already running."
        color_msg yellow WARNING
    else
        touch $PIDFILE && chown zabbix:zabbix $PIDFILE
        $DAEMON -c $CONF >/dev/null 2>&1
        if [  $? -eq 0 ]; then
            color_msg green SUCCESS && touch $LOCKFILE
        else
            color_msg red FAILED
            rm -f $PIDFILE
            exit 1
        fi
    fi
}

stop() {
    echo -n "Stopping $PROG : "
    PROC_PID=$(pgrep -P 1 -u zabbix ^$PROG)
    if [ -z "$PROC_PID" ]; then
        echo -n "is not running."
        color_msg yellow WARNING
    else
        kill -TERM ${PROC_PID} >/dev/null 2>&1
        while [ "$STOPTIME" -gt 0 ]; do
            kill -0 ${PROC_PID} >/dev/null 2>&1 || break
            STOPTIME=$(($STOPTIME-1))
            echo -n "." && sleep 0.001s
        done
        if [ "$STOPTIME" -le 0 ]; then
            color_msg red TIMEOUT && exit 1
        else
            color_msg green SUCCESS
            rm -f $PIDFILE $LOCKFILE
        fi
	fi
}

restart() {
        echo -n "Restart $PROG : "
        echo
        echo -en "\t" && stop
        echo -en "\t" && start
}

status() {
    PROC_PID=$(pgrep -P 1 -u zabbix ^$PROG)
    if [ -z "$PROC_PID" ];then
        echo "$PROG is stopped"
        exit 3
    else
        echo "$PROG (pid $PROC_PID) is running..."
        exit 0
    fi
}

quit() {
    echo -n "Quit $PROG : "
    PROC_PID=$(pgrep -P 1 -u zabbix ^$PROG)
    if [ -z "$PROC_PID" ]; then
        echo -n "is not running."
        color_msg yellow WARNING
    else
        kill -QUIT ${PROC_PID} >/dev/null 2>&1
        while [ "$STOPTIME" -gt 0 ]; do
            kill -0 ${PROC_PID} >/dev/null 2>&1 || break
            STOPTIME=$(($STOPTIME-1))
            echo -n "." && sleep 0.001s
        done
        if [ "$STOPTIME" -le 0 ]; then
            color_msg red TIMEOUT && exit 1
        else
            color_msg green SUCCESS
            rm -f $PIDFILE $LOCKFILE
        fi
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|try-restart)
        restart
        ;;
    reload|force-reload)
        restart
        ;;
    status)
        status
        ;;
    quit)
        quit
        ;;
    *)
       echo $"Usage: $0 {start|stop|restart|reload|status|quit}"
       exit 1
    ;;
esac
